// error types

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTRATIONFORM = "REGISTRATIONFORM";
export const OTPCONFIRMATION = "OTPCONFIRMATION";
export const USER_AUTH = "USER_AUTH";
export const USER_DB_DETAILS = "USER_DB_DETAILS";
export const PRIVACY_SETTINGS_OPTIONS = "PRIVACY_SETTINGS_OPTIONS";
export const NOTIFICATIONS_SETTINGS_OPTIONS = "NOTIFICATIONS_SETTINGS_OPTIONS";
export const SCREEN_LOADER = "SCREEN_LOADER";
export const ISVOICEMODALOPEN = "ISVOICEMODALOPEN";
export const HOME_POSTS = "HOME_POSTS";
export const FIREBASE_EXPO_APP = "FIREBASE_EXPO_APP";
